[book]
authors = ["lonerOrz"]
language = "en"
src = "docs"
title = "nuci - Declarative OpenWrt Config"

[output.html]
git-repository-url = "https://github.com/lonerOrz/openwrt-nix"
edit-url-template = "https://github.com/lonerOrz/openwrt-nix/edit/main/{path}"

[output.html.fold]
enable = true
